<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 7.2.2 (Python 3.10.12 on linux)" generated="2025-04-29T14:13:15.745150" rpa="false" schemaversion="5">
<suite id="s1" name="Calculator Tests" source="/home/nguyenvh/Sync/3a/stage_stet/projet_dho/robot-report-generator/tests/calculator_tests.robot">
<test id="s1-t1" name="Basic Addition" line="5">
<kw name="Open Calculator" owner="calculator_keywords">
<kw name="Open Browser" owner="SeleniumLibrary">
<msg time="2025-04-29T14:13:15.855409" level="INFO">Opening browser 'firefox' to base url 'http://localhost:3000'.</msg>
<arg>${app.url}</arg>
<arg>firefox</arg>
<doc>Opens a new browser instance to the optional ``url``.</doc>
<status status="PASS" start="2025-04-29T14:13:15.854558" elapsed="3.910064"/>
</kw>
<kw name="Wait Until Element Is Visible" owner="SeleniumLibrary">
<msg time="2025-04-29T14:13:22.891099" level="WARN">Keyword 'Capture Page Screenshot' could not be run on failure: Message: WebDriver session does not exist, or is not active
Stacktrace:
RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8
WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:199:5
InvalidSessionIDError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:469:5
assert.that/&lt;@chrome://remote/content/shared/webdriver/Assert.sys.mjs:559:13
assert.session@chrome://remote/content/shared/webdriver/Assert.sys.mjs:37:4
despatch@chrome://remote/content/marionette/server.sys.mjs:315:19
execute@chrome://remote/content/marionette/server.sys.mjs:289:16
onPacket/&lt;@chrome://remote/content/marionette/server.sys.mjs:262:20
onPacket@chrome://remote/content/marionette/server.sys.mjs:263:9
_onJSONObjectReady/&lt;@chrome://remote/content/marionette/transport.sys.mjs:494:20
</msg>
<msg time="2025-04-29T14:13:22.891415" level="FAIL">NoSuchWindowException: Message: Browsing context has been discarded
Stacktrace:
RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8
WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:199:5
NoSuchWindowError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:747:5
assert.that/&lt;@chrome://remote/content/shared/webdriver/Assert.sys.mjs:559:13
assert.open@chrome://remote/content/shared/webdriver/Assert.sys.mjs:147:4
GeckoDriver.prototype.findElements@chrome://remote/content/marionette/driver.sys.mjs:1822:15
despatch@chrome://remote/content/marionette/server.sys.mjs:318:40
execute@chrome://remote/content/marionette/server.sys.mjs:289:16
onPacket/&lt;@chrome://remote/content/marionette/server.sys.mjs:262:20
onPacket@chrome://remote/content/marionette/server.sys.mjs:263:9
_onJSONObjectReady/&lt;@chrome://remote/content/marionette/transport.sys.mjs:494:20
</msg>
<arg>${DISPLAY}</arg>
<doc>Waits until the element ``locator`` is visible.</doc>
<status status="FAIL" start="2025-04-29T14:13:19.764921" elapsed="3.127414">NoSuchWindowException: Message: Browsing context has been discarded
Stacktrace:
RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8
WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:199:5
NoSuchWindowError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:747:5
assert.that/&lt;@chrome://remote/content/shared/webdriver/Assert.sys.mjs:559:13
assert.open@chrome://remote/content/shared/webdriver/Assert.sys.mjs:147:4
GeckoDriver.prototype.findElements@chrome://remote/content/marionette/driver.sys.mjs:1822:15
despatch@chrome://remote/content/marionette/server.sys.mjs:318:40
execute@chrome://remote/content/marionette/server.sys.mjs:289:16
onPacket/&lt;@chrome://remote/content/marionette/server.sys.mjs:262:20
onPacket@chrome://remote/content/marionette/server.sys.mjs:263:9
_onJSONObjectReady/&lt;@chrome://remote/content/marionette/transport.sys.mjs:494:20
</status>
</kw>
<kw name="Log" owner="BuiltIn">
<arg>Opened calculator application</arg>
<doc>Logs the given message with the given level.</doc>
<status status="NOT RUN" start="2025-04-29T14:13:22.892547" elapsed="0.000038"/>
</kw>
<status status="FAIL" start="2025-04-29T14:13:15.853526" elapsed="7.039178">NoSuchWindowException: Message: Browsing context has been discarded
Stacktrace:
RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8
WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:199:5
NoSuchWindowError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:747:5
assert.that/&lt;@chrome://remote/content/shared/webdriver/Assert.sys.mjs:559:13
assert.open@chrome://remote/content/shared/webdriver/Assert.sys.mjs:147:4
GeckoDriver.prototype.findElements@chrome://remote/content/marionette/driver.sys.mjs:1822:15
despatch@chrome://remote/content/marionette/server.sys.mjs:318:40
execute@chrome://remote/content/marionette/server.sys.mjs:289:16
onPacket/&lt;@chrome://remote/content/marionette/server.sys.mjs:262:20
onPacket@chrome://remote/content/marionette/server.sys.mjs:263:9
_onJSONObjectReady/&lt;@chrome://remote/content/marionette/transport.sys.mjs:494:20
</status>
</kw>
<kw name="Perform Calculation" owner="calculator_keywords">
<arg>2</arg>
<arg>+</arg>
<arg>3</arg>
<status status="NOT RUN" start="2025-04-29T14:13:22.892928" elapsed="0.000036"/>
</kw>
<kw name="Verify Display Shows" owner="calculator_keywords">
<arg>5</arg>
<status status="NOT RUN" start="2025-04-29T14:13:22.893093" elapsed="0.000024"/>
</kw>
<kw name="Close Browser" owner="SeleniumLibrary" type="TEARDOWN">
<doc>Closes the current browser.</doc>
<status status="PASS" start="2025-04-29T14:13:22.893335" elapsed="0.007234"/>
</kw>
<status status="FAIL" start="2025-04-29T14:13:15.852636" elapsed="7.048074">NoSuchWindowException: Message: Browsing context has been discarded
Stacktrace:
RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8
WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:199:5
NoSuchWindowError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:747:5
assert.that/&lt;@chrome://remote/content/shared/webdriver/Assert.sys.mjs:559:13
assert.open@chrome://remote/content/shared/webdriver/Assert.sys.mjs:147:4
GeckoDriver.prototype.findElements@chrome://remote/content/marionette/driver.sys.mjs:1822:15
despatch@chrome://remote/content/marionette/server.sys.mjs:318:40
execute@chrome://remote/content/marionette/server.sys.mjs:289:16
onPacket/&lt;@chrome://remote/content/marionette/server.sys.mjs:262:20
onPacket@chrome://remote/content/marionette/server.sys.mjs:263:9
_onJSONObjectReady/&lt;@chrome://remote/content/marionette/transport.sys.mjs:494:20
</status>
</test>
<test id="s1-t2" name="Basic Subtraction" line="11">
<kw name="Open Calculator" owner="calculator_keywords">
<kw name="Open Browser" owner="SeleniumLibrary">
<msg time="2025-04-29T14:13:22.902203" level="INFO">Opening browser 'firefox' to base url 'http://localhost:3000'.</msg>
<arg>${app.url}</arg>
<arg>firefox</arg>
<doc>Opens a new browser instance to the optional ``url``.</doc>
<status status="PASS" start="2025-04-29T14:13:22.901548" elapsed="2.635850"/>
</kw>
<kw name="Wait Until Element Is Visible" owner="SeleniumLibrary">
<msg time="2025-04-29T14:13:27.202129" level="WARN">Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x7305171fe920&gt;: Failed to establish a new connection: [Errno 111] Connection refused')': /session/df3b21a6-5ac9-499f-9bd1-c0a748ad8f94/screenshot</msg>
<msg time="2025-04-29T14:13:27.202549" level="WARN">Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x7305171fee00&gt;: Failed to establish a new connection: [Errno 111] Connection refused')': /session/df3b21a6-5ac9-499f-9bd1-c0a748ad8f94/screenshot</msg>
<msg time="2025-04-29T14:13:27.203124" level="WARN">Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x7305171feda0&gt;: Failed to establish a new connection: [Errno 111] Connection refused')': /session/df3b21a6-5ac9-499f-9bd1-c0a748ad8f94/screenshot</msg>
<msg time="2025-04-29T14:13:27.203599" level="WARN">Keyword 'Capture Page Screenshot' could not be run on failure: HTTPConnectionPool(host='localhost', port=59083): Max retries exceeded with url: /session/df3b21a6-5ac9-499f-9bd1-c0a748ad8f94/screenshot (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x7305171fefb0&gt;: Failed to establish a new connection: [Errno 111] Connection refused'))</msg>
<arg>${DISPLAY}</arg>
<doc>Waits until the element ``locator`` is visible.</doc>
<status status="FAIL" start="2025-04-29T14:13:25.537600" elapsed="1.666142">Execution terminated by signal</status>
</kw>
<kw name="Log" owner="BuiltIn">
<arg>Opened calculator application</arg>
<doc>Logs the given message with the given level.</doc>
<status status="NOT RUN" start="2025-04-29T14:13:27.203951" elapsed="0.000035"/>
</kw>
<status status="FAIL" start="2025-04-29T14:13:22.901301" elapsed="4.302802">Execution terminated by signal</status>
</kw>
<kw name="Perform Calculation" owner="calculator_keywords">
<arg>8</arg>
<arg>-</arg>
<arg>3</arg>
<status status="NOT RUN" start="2025-04-29T14:13:27.204318" elapsed="0.000112"/>
</kw>
<kw name="Verify Display Shows" owner="calculator_keywords">
<arg>5</arg>
<status status="NOT RUN" start="2025-04-29T14:13:27.204566" elapsed="0.000025"/>
</kw>
<kw name="Close Browser" owner="SeleniumLibrary" type="TEARDOWN">
<msg time="2025-04-29T14:13:27.205337" level="WARN">Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x7305171ff880&gt;: Failed to establish a new connection: [Errno 111] Connection refused')': /session/df3b21a6-5ac9-499f-9bd1-c0a748ad8f94</msg>
<msg time="2025-04-29T14:13:27.205666" level="WARN">Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x7305171ff850&gt;: Failed to establish a new connection: [Errno 111] Connection refused')': /session/df3b21a6-5ac9-499f-9bd1-c0a748ad8f94</msg>
<msg time="2025-04-29T14:13:27.205955" level="WARN">Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x7305171ff9a0&gt;: Failed to establish a new connection: [Errno 111] Connection refused')': /session/df3b21a6-5ac9-499f-9bd1-c0a748ad8f94</msg>
<doc>Closes the current browser.</doc>
<status status="PASS" start="2025-04-29T14:13:27.204795" elapsed="0.001754"/>
</kw>
<status status="FAIL" start="2025-04-29T14:13:22.900996" elapsed="4.305647">Execution terminated by signal</status>
</test>
<test id="s1-t3" name="Basic Multiplication" line="17">
<tag>robot:exit</tag>
<status status="FAIL" start="2025-04-29T14:13:27.206881" elapsed="0.000260">Test execution stopped due to a fatal error.</status>
</test>
<test id="s1-t4" name="Basic Division" line="23">
<tag>robot:exit</tag>
<status status="FAIL" start="2025-04-29T14:13:27.207286" elapsed="0.000195">Test execution stopped due to a fatal error.</status>
</test>
<test id="s1-t5" name="Clear Function" line="29">
<tag>robot:exit</tag>
<status status="FAIL" start="2025-04-29T14:13:27.207610" elapsed="0.000237">Test execution stopped due to a fatal error.</status>
</test>
<test id="s1-t6" name="Complex Calculation" line="38">
<tag>robot:exit</tag>
<status status="FAIL" start="2025-04-29T14:13:27.207986" elapsed="0.000188">Test execution stopped due to a fatal error.</status>
</test>
<test id="s1-t7" name="Error Handling" line="50">
<tag>robot:exit</tag>
<status status="FAIL" start="2025-04-29T14:13:27.208303" elapsed="0.000175">Test execution stopped due to a fatal error.</status>
</test>
<test id="s1-t8" name="Decimal Numbers" line="59">
<tag>robot:exit</tag>
<status status="FAIL" start="2025-04-29T14:13:27.208607" elapsed="0.000189">Test execution stopped due to a fatal error.</status>
</test>
<status status="FAIL" start="2025-04-29T14:13:15.745952" elapsed="11.463146"/>
</suite>
<statistics>
<total>
<stat pass="0" fail="8" skip="0">All Tests</stat>
</total>
<tag>
<stat info="combined" combined="NOT robot:exit" pass="0" fail="2" skip="0">NOT robot:exit</stat>
</tag>
<suite>
<stat name="Calculator Tests" id="s1" pass="0" fail="8" skip="0">Calculator Tests</stat>
</suite>
</statistics>
<errors>
<msg time="2025-04-29T14:13:22.891099" level="WARN">Keyword 'Capture Page Screenshot' could not be run on failure: Message: WebDriver session does not exist, or is not active
Stacktrace:
RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8
WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:199:5
InvalidSessionIDError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:469:5
assert.that/&lt;@chrome://remote/content/shared/webdriver/Assert.sys.mjs:559:13
assert.session@chrome://remote/content/shared/webdriver/Assert.sys.mjs:37:4
despatch@chrome://remote/content/marionette/server.sys.mjs:315:19
execute@chrome://remote/content/marionette/server.sys.mjs:289:16
onPacket/&lt;@chrome://remote/content/marionette/server.sys.mjs:262:20
onPacket@chrome://remote/content/marionette/server.sys.mjs:263:9
_onJSONObjectReady/&lt;@chrome://remote/content/marionette/transport.sys.mjs:494:20
</msg>
<msg time="2025-04-29T14:13:27.202129" level="WARN">Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x7305171fe920&gt;: Failed to establish a new connection: [Errno 111] Connection refused')': /session/df3b21a6-5ac9-499f-9bd1-c0a748ad8f94/screenshot</msg>
<msg time="2025-04-29T14:13:27.202549" level="WARN">Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x7305171fee00&gt;: Failed to establish a new connection: [Errno 111] Connection refused')': /session/df3b21a6-5ac9-499f-9bd1-c0a748ad8f94/screenshot</msg>
<msg time="2025-04-29T14:13:27.203124" level="WARN">Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x7305171feda0&gt;: Failed to establish a new connection: [Errno 111] Connection refused')': /session/df3b21a6-5ac9-499f-9bd1-c0a748ad8f94/screenshot</msg>
<msg time="2025-04-29T14:13:27.203599" level="WARN">Keyword 'Capture Page Screenshot' could not be run on failure: HTTPConnectionPool(host='localhost', port=59083): Max retries exceeded with url: /session/df3b21a6-5ac9-499f-9bd1-c0a748ad8f94/screenshot (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x7305171fefb0&gt;: Failed to establish a new connection: [Errno 111] Connection refused'))</msg>
<msg time="2025-04-29T14:13:27.205337" level="WARN">Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x7305171ff880&gt;: Failed to establish a new connection: [Errno 111] Connection refused')': /session/df3b21a6-5ac9-499f-9bd1-c0a748ad8f94</msg>
<msg time="2025-04-29T14:13:27.205666" level="WARN">Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x7305171ff850&gt;: Failed to establish a new connection: [Errno 111] Connection refused')': /session/df3b21a6-5ac9-499f-9bd1-c0a748ad8f94</msg>
<msg time="2025-04-29T14:13:27.205955" level="WARN">Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x7305171ff9a0&gt;: Failed to establish a new connection: [Errno 111] Connection refused')': /session/df3b21a6-5ac9-499f-9bd1-c0a748ad8f94</msg>
</errors>
</robot>
